# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20bc44b15c2248c9c565ab2ac0109a7c18db0708dccb8641c8df3808719c2268960a58d060ddbcd307b167172cb7fed5849c61e4f95f4e25bb087c5d140f81c4

test:
  secret_key_base: 62ba2627b94493a11a5a7cb84454c5599d08da109c614ca5dcbe07e42af5d7e3247a435a3a87c440dbd20d099b932fb37815a50a974c754e4744b18d20d4b7bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
